//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""User"",
            ""id"": ""6c5f6b30-2731-4154-bbeb-93a7168b2fb2"",
            ""actions"": [
                {
                    ""name"": ""Vertical"",
                    ""type"": ""Value"",
                    ""id"": ""244443a1-82c1-4345-9048-b181e7428799"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""Scale(factor=5)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Horizontal"",
                    ""type"": ""Value"",
                    ""id"": ""5e8ef40b-02a2-410e-a977-e00d7ddbb452"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChoiceA"",
                    ""type"": ""Button"",
                    ""id"": ""4edcb19e-7b47-4229-8002-a713d09bf3fe"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChoiceB"",
                    ""type"": ""Button"",
                    ""id"": ""7a342f3e-7892-435a-ad9b-d5d94c2311b2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChoiceC"",
                    ""type"": ""Button"",
                    ""id"": ""4de37784-0f36-436f-afc5-3e8961badb56"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChoiceD"",
                    ""type"": ""Button"",
                    ""id"": ""1443b075-ab16-4f48-9c46-18c9fef84510"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChoiceBack"",
                    ""type"": ""Button"",
                    ""id"": ""851a3133-f259-4b1f-9269-6d5c45832920"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""hAxis"",
                    ""id"": ""b8f5aa57-2268-4937-88a1-80272b2521f3"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d74f14d8-c9cb-461d-beb8-4b6072601722"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""013904ad-ff7b-41ed-b041-d127c00f5cf3"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""vAxis"",
                    ""id"": ""0aa87e2c-3e7e-46a6-95e5-536512e0e598"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d9c7591b-6ec8-4ed3-a3af-628de492e67c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""02af9a3c-d772-4728-824c-45eab6d184fb"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3b134f43-c895-4767-9a43-39fbf4eb6ea9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChoiceA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7450d530-fa2e-4ca2-aab5-b2e064c84f57"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChoiceB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0c6711c-6176-449b-8565-b241fa266817"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChoiceC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0748776f-167c-47be-ae4c-793654144701"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChoiceD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7f3d2b6-6a75-41c3-bf72-16b9652de684"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChoiceBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e50c4898-ee48-440d-8087-88721c8a8c95"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChoiceBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // User
        m_User = asset.FindActionMap("User", throwIfNotFound: true);
        m_User_Vertical = m_User.FindAction("Vertical", throwIfNotFound: true);
        m_User_Horizontal = m_User.FindAction("Horizontal", throwIfNotFound: true);
        m_User_ChoiceA = m_User.FindAction("ChoiceA", throwIfNotFound: true);
        m_User_ChoiceB = m_User.FindAction("ChoiceB", throwIfNotFound: true);
        m_User_ChoiceC = m_User.FindAction("ChoiceC", throwIfNotFound: true);
        m_User_ChoiceD = m_User.FindAction("ChoiceD", throwIfNotFound: true);
        m_User_ChoiceBack = m_User.FindAction("ChoiceBack", throwIfNotFound: true);
    }

    ~@PlayerInput()
    {
        UnityEngine.Debug.Assert(!m_User.enabled, "This will cause a leak and performance issues, PlayerInput.User.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // User
    private readonly InputActionMap m_User;
    private List<IUserActions> m_UserActionsCallbackInterfaces = new List<IUserActions>();
    private readonly InputAction m_User_Vertical;
    private readonly InputAction m_User_Horizontal;
    private readonly InputAction m_User_ChoiceA;
    private readonly InputAction m_User_ChoiceB;
    private readonly InputAction m_User_ChoiceC;
    private readonly InputAction m_User_ChoiceD;
    private readonly InputAction m_User_ChoiceBack;
    public struct UserActions
    {
        private @PlayerInput m_Wrapper;
        public UserActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Vertical => m_Wrapper.m_User_Vertical;
        public InputAction @Horizontal => m_Wrapper.m_User_Horizontal;
        public InputAction @ChoiceA => m_Wrapper.m_User_ChoiceA;
        public InputAction @ChoiceB => m_Wrapper.m_User_ChoiceB;
        public InputAction @ChoiceC => m_Wrapper.m_User_ChoiceC;
        public InputAction @ChoiceD => m_Wrapper.m_User_ChoiceD;
        public InputAction @ChoiceBack => m_Wrapper.m_User_ChoiceBack;
        public InputActionMap Get() { return m_Wrapper.m_User; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UserActions set) { return set.Get(); }
        public void AddCallbacks(IUserActions instance)
        {
            if (instance == null || m_Wrapper.m_UserActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UserActionsCallbackInterfaces.Add(instance);
            @Vertical.started += instance.OnVertical;
            @Vertical.performed += instance.OnVertical;
            @Vertical.canceled += instance.OnVertical;
            @Horizontal.started += instance.OnHorizontal;
            @Horizontal.performed += instance.OnHorizontal;
            @Horizontal.canceled += instance.OnHorizontal;
            @ChoiceA.started += instance.OnChoiceA;
            @ChoiceA.performed += instance.OnChoiceA;
            @ChoiceA.canceled += instance.OnChoiceA;
            @ChoiceB.started += instance.OnChoiceB;
            @ChoiceB.performed += instance.OnChoiceB;
            @ChoiceB.canceled += instance.OnChoiceB;
            @ChoiceC.started += instance.OnChoiceC;
            @ChoiceC.performed += instance.OnChoiceC;
            @ChoiceC.canceled += instance.OnChoiceC;
            @ChoiceD.started += instance.OnChoiceD;
            @ChoiceD.performed += instance.OnChoiceD;
            @ChoiceD.canceled += instance.OnChoiceD;
            @ChoiceBack.started += instance.OnChoiceBack;
            @ChoiceBack.performed += instance.OnChoiceBack;
            @ChoiceBack.canceled += instance.OnChoiceBack;
        }

        private void UnregisterCallbacks(IUserActions instance)
        {
            @Vertical.started -= instance.OnVertical;
            @Vertical.performed -= instance.OnVertical;
            @Vertical.canceled -= instance.OnVertical;
            @Horizontal.started -= instance.OnHorizontal;
            @Horizontal.performed -= instance.OnHorizontal;
            @Horizontal.canceled -= instance.OnHorizontal;
            @ChoiceA.started -= instance.OnChoiceA;
            @ChoiceA.performed -= instance.OnChoiceA;
            @ChoiceA.canceled -= instance.OnChoiceA;
            @ChoiceB.started -= instance.OnChoiceB;
            @ChoiceB.performed -= instance.OnChoiceB;
            @ChoiceB.canceled -= instance.OnChoiceB;
            @ChoiceC.started -= instance.OnChoiceC;
            @ChoiceC.performed -= instance.OnChoiceC;
            @ChoiceC.canceled -= instance.OnChoiceC;
            @ChoiceD.started -= instance.OnChoiceD;
            @ChoiceD.performed -= instance.OnChoiceD;
            @ChoiceD.canceled -= instance.OnChoiceD;
            @ChoiceBack.started -= instance.OnChoiceBack;
            @ChoiceBack.performed -= instance.OnChoiceBack;
            @ChoiceBack.canceled -= instance.OnChoiceBack;
        }

        public void RemoveCallbacks(IUserActions instance)
        {
            if (m_Wrapper.m_UserActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUserActions instance)
        {
            foreach (var item in m_Wrapper.m_UserActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UserActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UserActions @User => new UserActions(this);
    public interface IUserActions
    {
        void OnVertical(InputAction.CallbackContext context);
        void OnHorizontal(InputAction.CallbackContext context);
        void OnChoiceA(InputAction.CallbackContext context);
        void OnChoiceB(InputAction.CallbackContext context);
        void OnChoiceC(InputAction.CallbackContext context);
        void OnChoiceD(InputAction.CallbackContext context);
        void OnChoiceBack(InputAction.CallbackContext context);
    }
}
