.TH "AbstractTask" 3 "Version 0.1" "Windows Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractTask
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBInternetTaskOne\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstartTask\fP ()"
.br
.ti -1c
.RI "void \fBcheckHazards\fP ()"
.br
.ti -1c
.RI "void \fBstopHazards\fP ()"
.br
.ti -1c
.RI "void \fBstartHazards\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBAbstractManager\fP > \fBhazardManagers\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Windows Project from the source code\&.
