.TH "AbstractManager" 3 "Version 0.1" "Windows Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStartHazard\fP ()"
.br
.ti -1c
.RI "void \fBStopHazard\fP ()"
.br
.ti -1c
.RI "bool \fBCanProgress\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Windows Project from the source code\&.
