.TH "GooseMove" 3 "Version 0.1" "Windows Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GooseMove
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBspeed\fP = 5\&.0f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Windows Project from the source code\&.
