.TH "InternetTaskOne" 3 "Version 0.1" "Windows Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InternetTaskOne
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractTask\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBOnWifiBtnClick\fP ()"
.br
.ti -1c
.RI "void \fBOnDiagnosisBtnClick\fP ()"
.br
.ti -1c
.RI "override void \fBstartTask\fP ()"
.br
.ti -1c
.RI "override void \fBcheckHazards\fP ()"
.br
.ti -1c
.RI "override void \fBstopHazards\fP ()"
.br
.ti -1c
.RI "override void \fBstartHazards\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBAbstractTask\fP
.in +1c
.ti -1c
.RI "void \fBstartTask\fP ()"
.br
.ti -1c
.RI "void \fBcheckHazards\fP ()"
.br
.ti -1c
.RI "void \fBstopHazards\fP ()"
.br
.ti -1c
.RI "void \fBstartHazards\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBAbstractTask\fP
.in +1c
.ti -1c
.RI "List< \fBAbstractManager\fP > \fBhazardManagers\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Windows Project from the source code\&.
