.TH "LoadingScript" 3 "Version 0.1" "Windows Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoadingScript
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStartLoading\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisLoaded\fP = false"
.br
.ti -1c
.RI "bool \fBcanContinue\fP = true"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Windows Project from the source code\&.
